### ISSUE TITLE
Make npm scripts usable on Windows cmd

### ISSUE THREAD

**Issue by Chaoses-Ib** [Ajaxy/telegram-tt#109]
The Windows cmd has different syntaxes and commands from bash. It will fail when executing the npm bash scripts, for example:
```cmd
C:\telegram-tt>npm run dev

> telegram-t@1.34.0 dev
> cross-env APP_ENV=development APP_VERSION=$(npm run print_version --silent) webpack serve --env mode=dev --env isDevServer --mode development --config ./webpack.config.js

'run' is not recognized as an internal or external command, operable program or batch file.
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: spawn run ENOENT
    at notFoundError (C:\telegram-tt\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\telegram-tt\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\telegram-tt\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\telegram-tt\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn run',
  path: 'run',
  spawnargs: [
    'print_version',
    '--silent)',
    'webpack',
    'serve',
    '--env',
    'mode=dev',
    '--env',
    'isDevServer',
    '--mode',
    'development',
    '--config',
    './webpack.config.js'
  ]
}
```
Since cmd is the default shell of Windows, it would be handy for people who want to contribute if we could make the scripts work on cmd.
An approach to implement this is to use [run-script-os](https://www.npmjs.com/package/run-script-os), for example:
```js
"scripts": {
  "dev": "run-script-os",
  "dev:default": "cross-env APP_ENV=development APP_VERSION=$(npm run print_version --silent) webpack serve --env mode=dev --env isDevServer --mode development --config ./webpack.config.js",
  "dev:win32": "FOR /F %v IN ('npm run print_version --silent') DO @cross-env APP_ENV=development APP_VERSION=%v webpack serve --env mode=dev --env isDevServer --mode development --config ./webpack.config.js",
  //...
}
```
Here is an article that discusses how to make scripts portable in more detail: [Making NPM scripts work cross platform](https://docgov.dev/posts/npm-scripts/).

**Comment by liangliangdep** [comment]
hi
  did you sovle this problem ? i have the same issue too...

**Comment by Chaoses-Ib** [comment]
Modify `scripts.dev` in `package.json` to:
```json
"dev": "FOR /F %v IN ('npm run print_version --silent') DO @cross-env APP_ENV=development APP_VERSION=%v webpack serve --env mode=dev --env isDevServer --mode development --config ./webpack.config.js"
```

You can also install bash on Windows (by installing Git for Windows) and change the default shell of npm to it:
```
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```

There is also a third solution - use a Linux virtual machine to run it, e.g., WSL 2.

**Comment by liangliangdep** [comment]
thans a lot !
