### ISSUE TITLE
run npm i get error

### ISSUE THREAD

**Issue by gosgos11** [Ajaxy/telegram-tt#151]
os     :ubuntu 20.04
node: 18.6.0 or 18.4.0
npm:  8.13.2 or 8.12.1

when run to reify:emoji-data-ios: timing reifyNode:node_modules/eslint-plugin-teactn get the follow error:

npm ERR! git dep preparation failed
npm ERR! command /root/.nvm/versions/node/v18.6.0/bin/node /root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c /tmp/install65849752332.sh
npm ERR! npm ERR! Failed to execute '/root/.nvm/versions/node/v18.6.0/bin/node /root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! npm ERR! node-pre-gyp info using node@18.6.0 | linux | x64
npm ERR! npm ERR! node-pre-gyp info check checked for "/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-linux-glibc-x64.tar.gz
npm ERR! npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-linux-glibc-x64.tar.gz 
npm ERR! npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.0 and node@18.6.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-linux-glibc-x64.tar.gz 
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@9.0.0
npm ERR! npm ERR! gyp info using node@18.6.0 | linux | x64
npm ERR! npm ERR! gyp info ok 
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@9.0.0
npm ERR! npm ERR! gyp info using node@18.6.0 | linux | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! npm ERR! gyp info spawn /usr/bin/python3
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'make',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/config.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.6.0/include/node/common.gypi',
npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.6.0',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.6.0/<(target_arch)/node.lib',
npm ERR! npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! npm ERR! gyp info spawn args   '--depth=.',
npm ERR! npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! npm ERR! gyp info spawn args   '--generator-output',
npm ERR! npm ERR! gyp info spawn args   'build',
npm ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! Package pixman-1 was not found in the pkg-config search path.
npm ERR! npm ERR! Perhaps you should add the directory containing `pixman-1.pc'
npm ERR! npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! npm ERR! No package 'pixman-1' found
npm ERR! npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! npm ERR! gyp ERR! configure error 
npm ERR! npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! npm ERR! gyp ERR! System Linux 5.4.0-81-generic
npm ERR! npm ERR! gyp ERR! command "/root/.nvm/versions/node/v18.6.0/bin/node" "/root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! npm ERR! gyp ERR! cwd /root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas
npm ERR! npm ERR! gyp ERR! node -v v18.6.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! npm ERR! gyp ERR! not ok 
npm ERR! npm ERR! node-pre-gyp ERR! build error 
npm ERR! npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v18.6.0/bin/node /root/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! npm ERR! node-pre-gyp ERR! System Linux 5.4.0-81-generic
npm ERR! npm ERR! node-pre-gyp ERR! command "/root/.nvm/versions/node/v18.6.0/bin/node" "/root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! npm ERR! node-pre-gyp ERR! cwd /root/.npm/_cacache/tmp/git-clonenJh7mK/node_modules/canvas
npm ERR! npm ERR! node-pre-gyp ERR! node -v v18.6.0
npm ERR! npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! npm ERR! node-pre-gyp ERR! not ok
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /root/.npm/_logs/2022-07-22T13_44_36_656Z-debug-0.log

**Comment by gosgos11** [comment]
use npm install --build-from-source is ok.
