### ISSUE TITLE
Handshake(Authentication) failed

### ISSUE THREAD

**Issue by ChenMoGe2** [Ajaxy/telegram-tt#164]
nodejs version:v16.17.0
npm version:8.15.0
run command:npm run dev

[2022-09-15T14:18:44.574Z] [ERROR] - [WebSocket connection failed attempt: 3]
MTProtoSender.js:194 TypeError: Cannot read properties of undefined (reading 'digest')
    at Hash.digest (crypto.js:104:57)
    at Object.sha256 (Helpers.js:215:19)
    at doAuthentication (Authenticator.ts:80:52)
    at async MTProtoSender._connect (MTProtoSender.js:278:25)
    at async MTProtoSender.connect (MTProtoSender.js:183:17)
    at async TelegramClient.connect (TelegramClient.js:198:31)
    at async TelegramClient.start (TelegramClient.js:888:13)
    at async init (client.ts:96:7)
    at async initApi (provider.ts:42:3)
    at async onmessage (worker.ts:23:7)

**Comment by Ajaxy** [comment]
What's your OS and browser?

**Comment by ChenMoGe2** [comment]
> What's your OS and browser?

Thanks I already solve it.It same as the issue [https://github.com/Ajaxy/telegram-tt/issues/51](url)
