### ISSUE TITLE
localhost lost connection 

### ISSUE THREAD

**Issue by AlexeyBelyakov** [Ajaxy/telegram-tt#372]
- setup .env file with my TELEGRAM_API_ID and TELEGRAM_API_HASH.
- install dependency 
- npm run dev
- successfully login with phone number 
- after 1 minute connection is always broken. Session on mobile device is also terminated.
[2024-07-06T18:27:11.487Z] [ERROR] - [Error: Not connected]
Tested with different telegram api. localhost Telegram K works fine.

**Comment by AlexeyBelyakov** [comment]
GramJSINVOKE users.GetFullUser
helpers.ts:189 GramJSINVOKE ERROR users.GetFullUser
log @ helpers.ts:189
client.ts:295 Error: RPCError undefined: SESSION_REVOKED (caused by users.GetFullUser)
    at RPCMessageToError (index.js:22:12)
    at MTProtoSender._handleRPCResult (MTProtoSender.js:809:27)
    at MTProtoSender._processMessage (MTProtoSender.js:728:15)
    at async MTProtoSender._recvLoop (MTProtoSender.js:657:17)

**Comment by abduraimovabdurahmon** [comment]
Menda ham shunday muammo
